# Dockerfile for Django Backend
FROM python:3.10-slim

# Set work directory
WORKDIR /app

RUN pip install --upgrade pip

COPY requirements.txt /app/

RUN pip install  -r requirements.txt

# Copy project
COPY . /app/

# Expose port
EXPOSE 8000

# Collect static files
RUN python manage.py collectstatic --noinput

# Run the application
CMD ["gunicorn", "backend.wsgi:application", "--bind", "0.0.0.0:8000"]
