# Generated by Django 5.1.4 on 2024-12-23 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teren',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokacija_grad', models.CharField(max_length=100)),
                ('lokacija_ulica', models.CharField(max_length=200)),
                ('slika', models.ImageField(blank=True, null=True, upload_to='teren_images/')),
                ('tip', models.CharField(choices=[('unutarnji', 'Unutarnji'), ('vanjski', 'Vanjski')], max_length=10)),
                ('dostupni_termini', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Igrac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('javni_profil', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vlasnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('javni_profil', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turnir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('datum_pocetka', models.DateTimeField()),
                ('datum_kraja', models.DateTimeField()),
                ('cijena_kotizacije', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nagrade', models.TextField()),
                ('opis', models.TextField()),
                ('otvorenost', models.CharField(choices=[('otvoren', 'Otvoren za prijave'), ('zavrsen', 'Turnir odigran')], max_length=10)),
                ('teren', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turniri', to='api.teren')),
                ('organizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turniri', to='api.vlasnik')),
            ],
        ),
        migrations.AddField(
            model_name='teren',
            name='vlasnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tereni', to='api.vlasnik'),
        ),
    ]
