# Generated by Django 5.1.4 on 2025-01-23 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='vrijeme',
            field=models.TimeField(default=datetime.datetime(2025, 1, 23, 12, 6, 23, 865882)),
        ),
        migrations.AlterField(
            model_name='post',
            name='vrijeme',
            field=models.TimeField(default=datetime.datetime(2025, 1, 23, 12, 6, 23, 864626)),
        ),
    ]
