# Generated by Django 5.1.4 on 2025-01-16 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='vrijeme',
            field=models.TimeField(default=datetime.datetime(2025, 1, 16, 14, 51, 24, 625685)),
        ),
        migrations.AlterField(
            model_name='post',
            name='vrijeme',
            field=models.TimeField(default=datetime.datetime(2025, 1, 16, 14, 51, 24, 624293)),
        ),
        migrations.AlterField(
            model_name='teren',
            name='dostupni_termini',
            field=models.JSONField(default=[{}]),
        ),
    ]
