# Generated by Django 5.1.4 on 2025-01-24 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igrac',
            name='slika',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='vrijeme',
            field=models.TimeField(default=datetime.datetime(2025, 1, 24, 14, 16, 57, 641463)),
        ),
        migrations.AlterField(
            model_name='post',
            name='vrijeme',
            field=models.TimeField(default=datetime.datetime(2025, 1, 24, 14, 16, 57, 641010)),
        ),
        migrations.AlterField(
            model_name='vlasnik',
            name='slika',
            field=models.URLField(blank=True, null=True),
        ),
    ]
