# Generated by Django 5.1.4 on 2025-01-23 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_komentar_vrijeme_alter_post_vrijeme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='vrijeme',
            field=models.TimeField(default=datetime.datetime(2025, 1, 23, 12, 37, 1, 677853)),
        ),
        migrations.AlterField(
            model_name='post',
            name='vrijeme',
            field=models.TimeField(default=datetime.datetime(2025, 1, 23, 12, 37, 1, 676581)),
        ),
        migrations.AlterField(
            model_name='termin',
            name='kraj',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='termin',
            name='pocetak',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='zauzetitermin',
            name='kraj',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='zauzetitermin',
            name='pocetak',
            field=models.DateTimeField(),
        ),
    ]
