# Generated by Django 5.1.4 on 2025-01-24 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_komentar_vrijeme_alter_post_vrijeme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='vrijeme',
            field=models.TimeField(default=datetime.datetime(2025, 1, 24, 11, 46, 43, 90918)),
        ),
        migrations.AlterField(
            model_name='post',
            name='vrijeme',
            field=models.TimeField(default=datetime.datetime(2025, 1, 24, 11, 46, 43, 90388)),
        ),
    ]
