# Generated by Django 5.1.4 on 2025-01-16 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_komentar_vrijeme_alter_post_vrijeme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='vrijeme',
            field=models.TimeField(default=datetime.datetime(2025, 1, 16, 15, 13, 52, 676111)),
        ),
        migrations.AlterField(
            model_name='post',
            name='vrijeme',
            field=models.TimeField(default=datetime.datetime(2025, 1, 16, 15, 13, 52, 674818)),
        ),
    ]
