# Generated by Django 5.1.4 on 2024-12-29 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teren_igrac_vlasnik_turnir_teren_vlasnik'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='igrac',
            name='slika',
            field=models.ImageField(blank=True, null=True, upload_to='igrac_images/'),
        ),
        migrations.AddField(
            model_name='igrac',
            name='telefon',
            field=models.CharField(default='0999696969', max_length=20),
        ),
        migrations.AddField(
            model_name='vlasnik',
            name='slika',
            field=models.ImageField(blank=True, null=True, upload_to='vlasnik_images/'),
        ),
        migrations.AddField(
            model_name='vlasnik',
            name='telefon',
            field=models.CharField(default='0999696969', max_length=20),
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('naslov', models.CharField(max_length=100)),
                ('opis', models.CharField(max_length=500)),
                ('broj_like', models.IntegerField(default=0)),
                ('broj_comment', models.IntegerField(default=0)),
                ('teren_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.teren')),
                ('turnir_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.turnir')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('naslov', models.CharField(max_length=100)),
                ('opis', models.CharField(max_length=500)),
                ('broj_like', models.IntegerField(default=0)),
                ('broj_comment', models.IntegerField(default=0)),
                ('teren_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.teren')),
                ('turnir_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.turnir')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
