# Generated by Django 5.1.4 on 2025-01-23 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_komentar_vrijeme_alter_post_vrijeme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='vrijeme',
            field=models.TimeField(default=datetime.datetime(2025, 1, 23, 12, 44, 23, 761788)),
        ),
        migrations.AlterField(
            model_name='post',
            name='vrijeme',
            field=models.TimeField(default=datetime.datetime(2025, 1, 23, 12, 44, 23, 760525)),
        ),
    ]
