# Generated by Django 5.1.4 on 2025-01-16 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_komentar_vrijeme_alter_post_vrijeme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='vrijeme',
            field=models.TimeField(default=datetime.datetime(2025, 1, 16, 16, 19, 45, 17288)),
        ),
        migrations.AlterField(
            model_name='post',
            name='vrijeme',
            field=models.TimeField(default=datetime.datetime(2025, 1, 16, 16, 19, 45, 15916)),
        ),
    ]
