# Generated by Django 5.1.4 on 2025-01-07 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_igrac_slika_igrac_telefon_vlasnik_slika_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentar',
            name='vrijeme',
            field=models.TimeField(default=datetime.datetime(2025, 1, 7, 13, 45, 45, 948637)),
        ),
        migrations.AddField(
            model_name='post',
            name='vrijeme',
            field=models.TimeField(default=datetime.datetime(2025, 1, 7, 13, 45, 45, 947633)),
        ),
    ]
