# Generated by Django 5.1.4 on 2025-01-07 15:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_komentar_vrijeme_post_vrijeme'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentar',
            name='post_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.post'),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='vrijeme',
            field=models.TimeField(default=datetime.datetime(2025, 1, 7, 16, 30, 34, 444151)),
        ),
        migrations.AlterField(
            model_name='post',
            name='vrijeme',
            field=models.TimeField(default=datetime.datetime(2025, 1, 7, 16, 30, 34, 443152)),
        ),
    ]
