# Generated by Django 5.1.4 on 2025-01-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_komentar_vrijeme_alter_post_vrijeme_and_more'),
        ('api', '0004_alter_komentar_vrijeme_alter_post_vrijeme'),
    ]

    operations = [
    ]
