# Generated by Django 5.1.4 on 2025-01-07 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_komentar_post_id_alter_komentar_vrijeme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='vrijeme',
            field=models.TimeField(default=datetime.datetime(2025, 1, 7, 17, 1, 13, 598920)),
        ),
        migrations.AlterField(
            model_name='post',
            name='vrijeme',
            field=models.TimeField(default=datetime.datetime(2025, 1, 7, 17, 1, 13, 598920)),
        ),
    ]
