# Generated by Django 5.1.4 on 2025-01-18 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20250118_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnirprijava',
            name='status',
            field=models.CharField(choices=[('prihvaćena', 'Prijava prihvaćena'), ('pending', 'Prijava čeka potvrdu')], default='pending', max_length=11),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='vrijeme',
            field=models.TimeField(default=datetime.datetime(2025, 1, 18, 10, 45, 3, 23287)),
        ),
        migrations.AlterField(
            model_name='post',
            name='vrijeme',
            field=models.TimeField(default=datetime.datetime(2025, 1, 18, 10, 45, 3, 22855)),
        ),
        migrations.AlterField(
            model_name='teren',
            name='dostupni_termini',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='turnir',
            name='otvorenost',
            field=models.CharField(choices=[('otvoren', 'Otvoren za prijave'), ('zavrsen', 'Turnir odigran')], default='otvoren', max_length=10),
        ),
    ]
