version: '3.9'

services:
  django:
    build:
      context: ./backend
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    

  react:
    build:
      context: ./frontend
    container_name: react_app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app